name: LLM_SSL
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=11.0.0=py39h613000e_0
  - async-timeout=4.0.2=py39h06a4308_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - datasets=2.12.0=py39h06a4308_0
  - dill=0.3.6=py39h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.46.1=h33aed49_1
  - huggingface_hub=0.14.1=py39h06a4308_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcurl=7.88.1=h91b91d3_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=hcc01f38_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - multiprocess=0.70.14=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_1
  - numexpr=2.8.4=py39hc78ab66_1
  - numpy=1.24.3=py39hf6e8229_1
  - numpy-base=1.24.3=py39h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyarrow=11.0.0=py39h992f0b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h5eee18b_1
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py39h5eee18b_1
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py39h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - scipy=1.10.1=py39hf6e8229_1
  - setuptools=66.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.0=py39_cu118
  - torchtriton=2.0.0=py39
  - torchvision=0.15.0=py39_cu118
  - tqdm=4.65.0=py39hb070fc8_0
  - typing-extensions=4.5.0=py39h06a4308_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - urllib3=1.26.15=py39h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wheel=0.38.4=py39h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.19.0
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==5.0.1
      - anyio==3.7.0
      - attrs==23.1.0
      - backoff==2.2.1
      - bitsandbytes==0.39.0
      - blis==0.7.9
      - catalogue==2.0.8
      - click==8.1.3
      - cmake==3.26.3
      - confection==0.0.4
      - contourpy==1.0.7
      - cycler==0.11.0
      - cymem==2.0.7
      - dataclasses-json==0.5.7
      - deepspeed==0.9.2
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.1
      - fastapi==0.95.2
      - ffmpy==0.3.0
      - fire==0.5.0
      - fonttools==4.39.4
      - fsspec==2023.5.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gradio==3.32.0
      - gradio-client==0.2.5
      - greenlet==2.0.2
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.2
      - httpx==0.24.1
      - huggingface==0.0.1
      - importlib-resources==5.12.0
      - jsonlines==3.1.0
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - langchain==0.0.183
      - langcodes==3.3.0
      - linkify-it-py==2.0.2
      - lit==16.0.5
      - markdown-it-py==2.2.0
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - multidict==6.0.4
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - ninja==1.11.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openai==0.27.7
      - openapi-schema-pydantic==1.2.4
      - opencc==1.1.6
      - orjson==3.8.14
      - packaging==23.1
      - pandas==2.0.1
      - pathtools==0.1.2
      - pathy==0.10.1
      - peft==0.3.0
      - preshed==3.0.8
      - protobuf==3.20.0
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - pydantic==1.10.8
      - pydub==0.25.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-multipart==0.0.6
      - pytz==2023.3
      - ratelimit==2.2.1
      - regex==2023.5.5
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==1.24.0
      - setproctitle==1.3.2
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sqlalchemy==2.0.15
      - srsly==2.4.6
      - starlette==0.27.0
      - sympy==1.12
      - tenacity==8.2.2
      - termcolor==2.3.0
      - thinc==8.1.10
      - tiktoken==0.4.0
      - tokenizers==0.13.3
      - toolz==0.12.0
      - torch==2.0.1
      - transformers==4.29.2
      - typer==0.7.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - uvicorn==0.22.0
      - wandb==0.15.3
      - wasabi==1.1.1
      - websockets==11.0.3
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /root/anaconda3/envs/LLM_SSL
